### PR TITLE
Modify the difference between powershell scripts and python scripts.

### PR DESCRIPTION
**Pull request by Jiangxin19**

### CODE REVIEW

**Comment by renxulei** [comment]
@Jiangxin19 What is the background you submit this PR?

**Comment by Jiangxin19** [comment]
Some scripts in PowerShell scripts have different GET results than Python scripts, which are too simplistic and incomplete, the code in this commit has been modified as required.

**Comment by renxulei** [comment]
Why do you use new script name? such as get_bmc_inventory2.psm1. It is not suggested.

**Comment by Jiangxin19** [comment]
I got it, I'll revise it again.

**Pull request closed without merging**
